module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contact_formatter: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  entityqueue: 0
  eventbrite_events: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  libraries: 0
  link: 0
  linkicon: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  midcamp_event_label_block: 0
  midcamp_tito: 0
  midcamp_utility: 0
  midcamp_vbo: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  scheduler: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  tito: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_extensions: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  config_installer: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  hatter_base: 0
  hatter_2019: 0
profile: config_installer
