_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: url
time_limit: 10
expire: 300
form_settings:
  user_register_form: true
  user_pass: false
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_article_form: false
  node_eventbrite_event_form: false
  node_job_form: false
  node_page_form: false
  node_sponsor_form: false
  node_summit_form: false
  node_topic_form: true
  node_training_form: true
  node_venue_form: false
  comment_comment_form: true
